CREATE TABLE user (
  idUser INT(11) NOT NULL,
  username VARCHAR(16) NOT NULL,
  password VARCHAR(60) NOT NULL,
  fullname VARCHAR(100) NOT NULL
);

ALTER TABLE user
  ADD PRIMARY KEY (idUser);

ALTER TABLE user
  MODIFY idUser INT(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT = 1;
